<?xml version='1.0'?>
<package format='3'>
  <name>hpp_centroidal_dynamics</name>
  <version>8.0.0</version>
  <description>Testing equilibrium of a system in contact with the environment</description>
  <author>Andrea Del Prete</author>
  <author>Pierre Fernbach</author>
  <author>Steve Tonneau</author>
  <maintainer email='guilhem.saurel@laas.fr'>Guilhem Saurel</maintainer>
  <license>GPL-2.0-only</license>

  <depend>boost</depend>
  <depend>coinor-libclp-dev</depend>
  <depend>eigen</depend>
  <depend>eigenpy</depend>
  <depend>libcdd-dev</depend>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>jrl_cmakemodules</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
